version: '3'
services:
  web:
    build: .
    ports:
      - "56733:80"
    volumes:
      - ./:/app
      - db-data:/app/backend/lookupTables
    environment:
      FLASK_ENV: development
volumes:
  db-data: