input_folder = "../dataProcessing/dat/"
output_folder = "../output/allInstructorsCSVs/"
instructor_dance_folder = "../output/instructorDances/"
concatenated_csvs_folder = "../output/concatenated/"
special_rates_path = "../lookupTables/pricing-options.csv"
all_classes_file = "00-01-Class-All.csv"